/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    entries: Entry;
    news: News;
    jobs: Job;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    entries: EntriesSelect<false> | EntriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cover?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'moderator' | 'editor';
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries".
 */
export interface Entry {
  id: number;
  entryType: 'startup' | 'community' | 'business' | 'consultory' | 'research-center' | 'person';
  name: string;
  /**
   * URL-friendly identifier. Auto-generated from name if left empty.
   */
  slug: string;
  tagline?: string | null;
  city:
    | 'global'
    | 'ahome'
    | 'angostura'
    | 'badiraguato'
    | 'choix'
    | 'concordia'
    | 'cosala'
    | 'culiacan'
    | 'el-fuerte'
    | 'elota'
    | 'escuinapa'
    | 'guasave'
    | 'mazatlan'
    | 'mocorito'
    | 'navolato'
    | 'rosario'
    | 'salvador-alvarado'
    | 'san-ignacio'
    | 'sinaloa-de-leyva';
  state?: string | null;
  country?: string | null;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  verified?: boolean | null;
  featured?: boolean | null;
  /**
   * Full URL (https://...)
   */
  website?: string | null;
  /**
   * X/Twitter handle
   */
  x?: string | null;
  /**
   * Instagram handle
   */
  instagram?: string | null;
  /**
   * LinkedIn URL or handle
   */
  linkedin?: string | null;
  /**
   * GitHub username
   */
  github?: string | null;
  /**
   * YouTube channel URL
   */
  youtube?: string | null;
  publishDate?: string | null;
  /**
   * better-auth user ID of the entry owner
   */
  owner?: string | null;
  /**
   * Rejection reason or feedback for the entry owner
   */
  moderationNote?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  foundedYear?: number | null;
  stage?: ('Idea' | 'Bootstrap' | 'Pre-seed' | 'Seed' | 'Serie A' | 'Serie B+' | 'Establecida') | null;
  teamSize?: ('1-5' | '6-15' | '16-50' | '51-200' | '200+') | null;
  sector?:
    | (
        | 'Desarrollo Web'
        | 'Desarrollo Mobile'
        | 'SaaS'
        | 'Fintech'
        | 'Edtech'
        | 'HealthTech'
        | 'AgriTech'
        | 'E-commerce'
        | 'IA / Machine Learning'
        | 'Ciberseguridad'
        | 'IoT'
        | 'MarTech'
        | 'LegalTech'
        | 'Logística'
        | 'Gaming'
        | 'Blockchain / Web3'
        | 'Cloud / Infraestructura'
        | 'Data & Analytics'
        | 'Consultoría IT'
        | 'Automatización'
        | 'Otro'
      )
    | null;
  services?:
    | {
        service: string;
        id?: string | null;
      }[]
    | null;
  technologies?:
    | {
        technology: string;
        id?: string | null;
      }[]
    | null;
  hiring?: boolean | null;
  hiringUrl?: string | null;
  businessModel?: ('B2B' | 'B2C' | 'B2B2C' | 'Marketplace' | 'SaaS' | 'Freemium' | 'Open Source' | 'Otro') | null;
  memberCount?: number | null;
  meetupFrequency?:
    | ('Permanente (online)' | 'Semanal' | 'Quincenal' | 'Mensual' | 'Trimestral' | 'Por evento' | 'Otro')
    | null;
  discord?: string | null;
  telegram?: string | null;
  platform?: ('Discord' | 'Telegram' | 'Slack' | 'WhatsApp' | 'Presencial' | 'Otro') | null;
  focusAreas?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  role?: string | null;
  company?: string | null;
  skills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  availableForHire?: boolean | null;
  availableForMentoring?: boolean | null;
  email?: string | null;
  /**
   * Portfolio URL
   */
  portfolio?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL slug. Auto-generated from title if left empty.
   */
  slug: string;
  /**
   * Short summary for listings and SEO (max 200 chars)
   */
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  publishDate: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * URL slug. Auto-generated from title if left empty.
   */
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'full-time' | 'part-time' | 'contract' | 'freelance' | 'volunteer';
  modality: 'remote' | 'in-person' | 'hybrid';
  city?:
    | (
        | 'global'
        | 'ahome'
        | 'angostura'
        | 'badiraguato'
        | 'choix'
        | 'concordia'
        | 'cosala'
        | 'culiacan'
        | 'el-fuerte'
        | 'elota'
        | 'escuinapa'
        | 'guasave'
        | 'mazatlan'
        | 'mocorito'
        | 'navolato'
        | 'rosario'
        | 'salvador-alvarado'
        | 'san-ignacio'
        | 'sinaloa-de-leyva'
      )
    | null;
  /**
   * Flexible format: "$15k/mo", "Voluntario", "Equity", etc.
   */
  compensation?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL or email for applicants to contact
   */
  contactUrl: string;
  /**
   * better-auth user ID of the poster
   */
  postedBy?: string | null;
  /**
   * Rejection reason or feedback for the job poster
   */
  moderationNote?: string | null;
  /**
   * Link to the company/org that posted this job (optional)
   */
  entry?: (number | null) | Entry;
  /**
   * Job listing expiration date (default: 30 days from creation)
   */
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  organizer?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  date: string;
  /**
   * e.g. 10:00 AM
   */
  startTime?: string | null;
  /**
   * e.g. 12:00 PM
   */
  endTime?: string | null;
  /**
   * Venue name or address
   */
  location?: string | null;
  /**
   * Google Maps link
   */
  mapsUrl?: string | null;
  modality: 'in-person' | 'online' | 'hybrid';
  /**
   * Video call link (Zoom, Meet, etc.)
   */
  meetLink?: string | null;
  /**
   * Event page URL
   */
  url?: string | null;
  /**
   * Registration link
   */
  registerUrl?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'entries';
        value: number | Entry;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cover?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries_select".
 */
export interface EntriesSelect<T extends boolean = true> {
  entryType?: T;
  name?: T;
  slug?: T;
  tagline?: T;
  city?: T;
  state?: T;
  country?: T;
  logo?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  verified?: T;
  featured?: T;
  website?: T;
  x?: T;
  instagram?: T;
  linkedin?: T;
  github?: T;
  youtube?: T;
  publishDate?: T;
  owner?: T;
  moderationNote?: T;
  body?: T;
  foundedYear?: T;
  stage?: T;
  teamSize?: T;
  sector?: T;
  services?:
    | T
    | {
        service?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  hiring?: T;
  hiringUrl?: T;
  businessModel?: T;
  memberCount?: T;
  meetupFrequency?: T;
  discord?: T;
  telegram?: T;
  platform?: T;
  focusAreas?:
    | T
    | {
        area?: T;
        id?: T;
      };
  role?: T;
  company?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  availableForHire?: T;
  availableForMentoring?: T;
  email?: T;
  portfolio?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  author?: T;
  publishDate?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  type?: T;
  modality?: T;
  city?: T;
  compensation?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  contactUrl?: T;
  postedBy?: T;
  moderationNote?: T;
  entry?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  organizer?: T;
  description?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  mapsUrl?: T;
  modality?: T;
  meetLink?: T;
  url?: T;
  registerUrl?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}